site_name: AngularJS to React
site_url: https://marketplace.visualstudio.com/items?itemName=maxbilbow.ng2react-vscode&ssr=false#overview
nav:
    - Home: index.md
    - Extensions: VSCode.md
    - "@ng2react/support": ng2react-support.md 
    - About: about.md
    - MkDocs: MkDocs.md
theme: 
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - tsx
        - jsx
        - typescript
        - javascript