site_name: AngularJS to React
site_url: https://marketplace.visualstudio.com/items?itemName=maxbilbow.ng2react-vscode&ssr=false#overview
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - User Guide: user-guide.md
    - "@ng2react/support": ng2react-support.md 
    - Contribute: contribute.md
    - About: about.md
theme: 
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - tsx
        - jsx
        - typescript
        - javascript