site_name: AngularJS to React
site_url: https://marketplace.visualstudio.com/items?itemName=maxbilbow.ng2react-vscode&ssr=false#overview
nav:
    - Home: index.md
    - Arc24: arc42.md
    - About: about.md
    - MkDocs: MkDocs.md
theme: readthedocs